server:
  port: 9002
  
spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo
    
  jpa:
   
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true   
  

    

  

  
  
    
  
  
